### ISSUE TITLE
Connection refused to Elasticsearch service during pio status

### ISSUE THREAD

**Issue by atfergus** [shimamoto/docker-predictionio#1]
Following the directions in the README, it seems like Elasticsearch is not initializing correctly.

I get the following output while checking services status:
```
pio@8264c3127850:/$ jps -l
4178 sun.tools.jps.Jps
1315 org.apache.predictionio.tools.console.Console
3716 org.apache.hadoop.hbase.master.HMaster
4013 org.apache.predictionio.tools.console.Console


pio@8264c3127850:/$ pio status
[INFO] [Management$] Inspecting PredictionIO...
[INFO] [Management$] PredictionIO 0.12.0-incubating is installed at /PredictionIO-0.12.0-incubating
[INFO] [Management$] Inspecting Apache Spark...
[INFO] [Management$] Apache Spark is installed at /PredictionIO-0.12.0-incubating/vendors/spark-2.1.1-bin-hadoop2.7
[INFO] [Management$] Apache Spark 2.1.1 detected (meets minimum requirement of 1.3.0)
[INFO] [Management$] Inspecting storage backend connections...
[INFO] [Storage$] Verifying Meta Data Backend (Source: ELASTICSEARCH)...
[ERROR] [Management$] Unable to connect to all storage backends successfully.
The following shows the error message from the storage backend.

Connection refused (java.net.ConnectException)

Dumping configuration of initialized storage backend sources.
Please make sure they are correct.

Source Name: ELASTICSEARCH; Type: elasticsearch; Configuration: HOME -> /PredictionIO-0.12.0-incubating/vendors/elasticsearch-5.5.2, HOSTS -> localhost, PORTS -> 9200, CLUSTERNAME -> predictionio, TYPE -> elasticsearch
```

**Comment by shimamoto** [comment]
Are you using Docker for Mac? If so, the default Docker for Mac (and presumably Windows as well) configuration limits Docker to 2GB of memory. The default heap size for Elasticsearch 5.5.x is also 2GB which means the Elasticsearch container will immediately exit (it's killed due to out of memory).

I configured Docker for Mac to allow for more than 2GB of memory.

**Comment by PedroCardoso1** [comment]
I also received the same output and can not fix
Any idea?
I have 2Gb of free memory.

**Comment by atfergus** [comment]
@PedroCardoso1 When I received this error, I followed shimamoto's suggestion to up the memory allowed for Docker and it fixed the issue.

**Comment by PedroCardoso1** [comment]
Thank @atfergus !
I'll do it

**Comment by PedroCardoso1** [comment]
I did not change my memory.

Sorted out!
To solve this problem you have to create a new user and a password, then give permission for that user only to the folder where the PredictionIO is.

Checking PredictionIO Status...
[INFO] [Management$] Inspecting PredictionIO...
[INFO] [Management$] PredictionIO 0.12.0-incubating is installed at /PredictionIO/predictionio-setup-master/predictionio
[INFO] [Management$] Inspecting Apache Spark...
[INFO] [Management$] Apache Spark is installed at /PredictionIO/predictionio-setup-master/spark
[INFO] [Management$] Apache Spark 2.2.0 detected (meets minimum requirement of 1.3.0)
[INFO] [Management$] Inspecting storage backend connections...
[INFO] [Storage$] Verifying Meta Data Backend (Source: ELASTICSEARCH)...
[INFO] [Storage$] Verifying Model Data Backend (Source: LOCALFS)...
[INFO] [Storage$] Verifying Event Data Backend (Source: ELASTICSEARCH)...
[INFO] [Storage$] Test writing to Event Store (App Id 0)...
[INFO] [Management$] Your system is all ready to go.

**Comment by rubeshan** [comment]
I also had similar issue. 
I noticed that it took a while for the system to start up. Once everything is up, your system should be good to go.


root@8aefefde4118:/apache-predictionio# pio status
[INFO] [Management$] Inspecting PredictionIO...
[INFO] [Management$] PredictionIO 0.12.0-incubating is installed at /PredictionIO
[INFO] [Management$] Inspecting Apache Spark...
[INFO] [Management$] Apache Spark is installed at /spark
[INFO] [Management$] Apache Spark 2.2.1 detected (meets minimum requirement of 1.3.0)
[INFO] [Management$] Inspecting storage backend connections...
[INFO] [Storage$] Verifying Meta Data Backend (Source: ELASTICSEARCH)...
[ERROR] [Management$] Unable to connect to all storage backends successfully.
The following shows the error message from the storage backend.

Connection refused (java.net.ConnectException)

Dumping configuration of initialized storage backend sources.
Please make sure they are correct.

Source Name: ELASTICSEARCH; Type: elasticsearch; Configuration: TYPE -> elasticsearch, HOME -> /elasticsearch



run "jps" to ensure the required processes are up.
root@6712af0b407c:/var/log/elasticsearch# jps
1041 Jps
34 Console
55 Elasticsearch
29 Console
30 HMaster


Then run "pio status"
root@6712af0b407c:/var/log/elasticsearch# pio status
[INFO] [Management$] Inspecting PredictionIO...
[INFO] [Management$] PredictionIO 0.12.0-incubating is installed at /PredictionIO
[INFO] [Management$] Inspecting Apache Spark...
[INFO] [Management$] Apache Spark is installed at /spark
[INFO] [Management$] Apache Spark 2.2.1 detected (meets minimum requirement of 1.3.0)
[INFO] [Management$] Inspecting storage backend connections...
[INFO] [Storage$] Verifying Meta Data Backend (Source: ELASTICSEARCH)...
[INFO] [Storage$] Verifying Model Data Backend (Source: LOCALFS)...
[INFO] [Storage$] Verifying Event Data Backend (Source: HBASE)...
[INFO] [Storage$] Test writing to Event Store (App Id 0)...
[INFO] [HBLEvents] The namespace pio_event doesn't exist yet. Creating now...
[INFO] [HBLEvents] The table pio_event:events_0 doesn't exist yet. Creating now...
[INFO] [HBLEvents] Removing table pio_event:events_0...
[INFO] [Management$] Your system is all ready to go.
